### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by BlueHero233** [BlueHero233/ZTNHRefreshed#1]
- [ ] Extruder Patterns
- [ ] Steam Valves
- [ ] Fluid Cells
- [ ] Single Use/Rechargable Batteries
- [ ] Ore Prospectors
- [ ] Fireclay
- [ ] Raw/Pico Wafers
- [ ] Lapotronic Super Capacitor Casings
- [ ] AE2 Fluid Crafting
- [ ] Thaum/Forbidden Magic Shards
- [ ] Galacticraft
- [ ] Minecraft New Textures
- [ ] CTM Textures Coils, Glass, Machine Casings
- [ ] Preferably get rid of all 32x32 textures

**Comment by BlueHero233** [comment]
- [ ] Gallium Arsenide Crystals (not dusts!!)
